version: "3.8"

services:
  ds-java:
    image: itzg/minecraft-server
    env_file:
      - ./settings.env
    ports:
      - 25565:25565
      - 25575:25575 # remote RCON
      - 8123:8123   # dynmap
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  overviewer:
