#!/usr/bin/env bash
# Client on host
PASSWD=$(cat docker-compose.yml | grep RCON_PASSWORD | sed 's/^.*RCON_PASSWORD:\s*"//' | sed 's/"$//')
HOST=$(dig $(hostname).local A +short | head -n 1)
PORT=25575

#rconshell --prompt "RCON $(hostname)> " $PASSWD@$HOST:$PORT

# Container
SERVICE=ds-java
docker-compose exec $SERVICE rcon-cli
