#!/usr/bin/env bash
# Folder structure:
#   ~/
#     ├── minecraft.git/    # bare git repository
#     └── minecraft/        # initially empty
#
# The bare git repository is initialised with
#       cd ~/minecraft.git
#       git init --bare
#
# This script is copied to:
#       ~/minecraft.git/hooks/post-receive
#
# The host deploying the system (eg: your computer) has the prod
#   server as a remote:
#       git remote add prod ssh://youripaddress:/home/minecraft/minecraft.git
# Then, to deploy from the same box:
#       git checkout master
#       git push prod

read oldrev newrev refname
echo params: $oldrev $newrev $refname

# tool versions
python --version
docker --version
docker-compose --version

set -euxo pipefail

# Directories
ROOT=~minecraft
TARGET=$ROOT/minecraft
TEMP=$ROOT/minecraft.tmp
REPO=$ROOT/minecraft.git

export COMPOSE_FILE=docker-compose.yml

# --- Chekcout to temp
rm -rf $TEMP
mkdir -p $TEMP
git --work-tree="$TEMP" --git-dir="$REPO" \
    checkout --force --quiet "$refname"

# --- Stop Services
pushd $TARGET
if [ -e $COMPOSE_FILE ] ; then
    docker-compose stop
fi
popd

# --- Deploy (temp -> target)
rm -rf $TARGET
mv $TEMP $TARGET

# --- Restart & Build
pushd $TARGET
# Build & start services
docker-compose build
docker-compose up -d
popd
